# Catppuccin Theme colors
# [[colors.indexed_colors]]
# color = "#FAB387"
# index = 16
#
# [[colors.indexed_colors]]
# color = "#F5E0DC"
# index = 17
#
# [colors.bright]
# black = "#585B70"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#A6ADC8"
# yellow = "#F9E2AF"
#
# [colors.cursor]
# cursor = "#F5E0DC"
# text = "#1E1E2E"
#
# [colors.dim]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [colors.hints.end]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [colors.hints.start]
# background = "#F9E2AF"
# foreground = "#1E1E2E"
#
# [colors.normal]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [colors.primary]
# background = "#1E1E2E"
# bright_foreground = "#CDD6F4"
# dim_foreground = "#CDD6F4"
# foreground = "#CDD6F4"
#
# [colors.search.focused_match]
# background = "#A6E3A1"
# foreground = "#1E1E2E"
#
# # [colors.search.footer_bar]
# # background = "#A6ADC8"
# # foreground = "#1E1E2E"
#
# [colors.search.matches]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [colors.selection]
# background = "#F5E0DC"
# text = "#1E1E2E"
#
# [colors.vi_mode_cursor]
# cursor = "#B4BEFE"
# text = "#1E1E2E"


# Kanagawa Theme Colors
[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

[colors.normal]
black =   '0x090618'
red =     '0xc34043'
green =   '0x76946a'
yellow =  '0xc0a36e'
blue =    '0x7e9cd8'
magenta = '0x957fb8'
cyan =    '0x6a9589'
white =   '0xc8c093'

[colors.bright]
black =   '0x727169'
red =     '0xe82424'
green =   '0x98bb6c'
yellow =  '0xe6c384'
blue =    '0x7fb4ca'
magenta = '0x938aa9'
cyan =    '0x7aa89f'
white =   '0xdcd7ba'

[colors.selection]
background = '0x2d4f67'
foreground = '0xc8c093'

[[colors.indexed_colors]]
index = 16
color = '0xffa066'

[[colors.indexed_colors]]
index = 17
color = '0xff5d62'
